# specify language
language: java
jdk:
- 1.8
sudo: true
script: mvn clean verify

# configure which branches to run
branches:
  # whitelist
  only:
    - TravisCIProject
    - master
    - /^deploy-.*$/ # regex ok
  # blacklist
  except:
    - TravisIntegration 
    - TravisCITool
    - GitTravisCI-1

after_script: # here's a build step block
- echo "Say Hello"

after_script:
- test $TRAVIS_PULL_REQUEST = false \
  && echo "not a pull request" \
  && git push \
  
notifications: # set notification options
  email:
    recipients:
      - amkaur@qasource.com

    # change is when the repo status goes from pass to fail or vice versa
    on_success: always
    on_failure: always
    
  # Or we could just disable all email
  # email: false
  
       
## begin build steps
####################

 # install: ./install-dependencies.sh
